version: "3"

services:
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ec_shop
      TZ: Asia/Taipei
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - shop_net

  # backend:
  #   build: .
  #   restart: always
  #   links:
  #     - db
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - shop_net
  #   depends_on:
  #     - db
  #   command: sh -c "npm run start:dev"

  #   volumes:
  #     - backend_data:/ec_shop_backend

volumes:
  mysql_data:
  # backend_data:


networks:
  shop_net:
    driver: bridge